.eslintrc.js
Temporarily removed restrictions to EOL of files.
=> ESLint linebreak-style fix for windows

cypress/support/util.js, package-lock.json, package.json
Added pre-commit hook
`npm install` after merging
=> Precommit hook

cypress/integration/v2/blocks/divider.spec.js
=> added divider style tests

cypress/integration/v2/blocks/icon.spec.js, cypress/support/advanced.js, cypress/support/commands/index.js, cypress/support/commands/setup.js, cypress/support/commands/styles.js, cypress/support/helpers.js, cypress/support/modules.js, cypress/support/util.js
=> Icon refactor

cypress/integration/v2/blocks/header.spec.js, cypress/support/commands/inspector.js, cypress/support/commands/styles.js, cypress/support/helpers.js
=> added header tests

cypress/integration/v2/blocks/icon-list.spec.js, cypress/support/commands/styles.js, cypress/support/helpers.js, cypress/support/util.js
=> added style tests

cypress/integration/v2/blocks/cta.spec.js
=> added cta style tests

cypress.json, cypress/integration/v2/blocks/expand.spec.js, package.json
=> refactor expand test

cypress.json, cypress/integration/v2/blocks/separator.spec.js
=> separator refactor tests

cypress.json, cypress/integration/v2/blocks/feature-grid.spec.js, cypress/support/commands/inspector.js, cypress/support/commands/styles.js, cypress/support/helpers.js
=> feature grid style tests

cypress/integration/v2/blocks/heading.spec.js
=> added align auto assert

cypress.json, cypress/integration/v2/blocks/count-up.spec.js
=> count up style tests

cypress.json, cypress/integration/v2/blocks/icon.spec.js
=> refactored icon test

cypress/integration/v2/blocks/accordion.spec.js, cypress/integration/v2/blocks/blockquote.spec.js, cypress/integration/v2/blocks/button.spec.js, cypress/integration/v2/blocks/count-up.spec.js, cypress/integration/v2/blocks/cta.spec.js, cypress/integration/v2/blocks/expand.spec.js, cypress/integration/v2/blocks/feature-grid.spec.js, cypress/integration/v2/blocks/header.spec.js, cypress/integration/v2/blocks/heading.spec.js, cypress/integration/v2/blocks/icon-list.spec.js, cypress/integration/v2/blocks/icon.spec.js, cypress/integration/v2/blocks/text.spec.js, cypress/support/helpers.js
=> added typography helper

cypress.json, cypress/integration/v2/blocks/card.spec.js
=> added card style tests

cypress.json, cypress/integration/v2/blocks/notification.spec.js, cypress/support/commands/styles.js
=> added notification style tests

cypress.json, cypress/integration/v2/blocks/number-box.spec.js, cypress/support/commands/styles.js, cypress/support/helpers.js
Cannot test fully due to having a Windows machine
=> Number box test

cypress/support/gutenberg/plugins/blockSnapshots.js
Passing tests
** removed the blocks with open PRs
=> added block snapshot fix

cypress/integration/v2/blocks/button.spec.js, cypress/integration/v2/blocks/card.spec.js, cypress/integration/v2/blocks/count-up.spec.js, cypress/integration/v2/blocks/cta.spec.js, cypress/integration/v2/blocks/feature-grid.spec.js, cypress/integration/v2/blocks/header.spec.js, cypress/integration/v2/blocks/notification.spec.js, cypress/integration/v2/blocks/spacer.spec.js, cypress/support/stackable/commands/controls.js, cypress/support/stackable/helpers/index.js
=> Added options in assertTypography

cypress.json, cypress/integration/v2/blocks/pricing-box.spec.js
Tests do not pass in the frontend due to the following issue: https://github.com/gambitph/Stackable/issues/1069
=> Pricing box test

cypress.json, cypress/integration/v2/blocks/video-popup.spec.js
Opened Issues:
Block title spacing in frontend
https://github.com/gambitph/Stackable/issues/1070
the tests are passing when the block title spacing assertion is removed:
=> added video popup style tests

cypress.json, cypress/integration/v2/blocks/team-member.spec.js, cypress/support/gutenberg/commands/controls.js, cypress/support/gutenberg/commands/inspector.js, cypress/support/stackable/commands/controls.js
Tests do not pass due to the following issue: https://github.com/gambitph/Stackable/issues/1074
=> added team member test

cypress.json, cypress/integration/v2/blocks/columns.spec.js, cypress/support/gutenberg/commands/controls.js, cypress/support/stackable/commands/controls.js, cypress/support/stackable/helpers/modules.js
=> added columns style test

cypress/integration/v2/blocks/pricing-box.spec.js, cypress/support/stackable/helpers/index.js
All desktopStyle tests are passing
=> added font family assertion in assertTypography

cypress/support/gutenberg/commands/assertions.js, cypress/support/gutenberg/commands/blocks.js, cypress/support/gutenberg/commands/editor.js, cypress/support/gutenberg/plugins/blockSnapshots.js, cypress/support/gutenberg/util.js, cypress/support/stackable/commands/global-settings.js, cypress/support/stackable/helpers/index.js
Modified documentation for the ff:
- gutenberg/commands/inspector.js -> waitLoader
- gutenberg/plugins/blockSnapshots.js -> BlockSnapshots
=> edited documentation

cypress/support/gutenberg/commands/editor.js
Fix for Issue #122 
Fixes #122
=> revised publish command if statement

cypress/integration/v2/blocks/feature-grid.spec.js
Fix for Issue #83 
Added assertComputedStyle for button opacity as well
=> added button design and opacity test to feature grid test

cypress/integration/v2/blocks/column.spec.js, cypress/integration/v2/blocks/columns.spec.js
=> added column spec, temporary fix for #124

cypress/integration/v2/blocks/expand.spec.js, cypress/integration/v2/blocks/feature-grid.spec.js, cypress/integration/v2/blocks/heading.spec.js, cypress/integration/v2/blocks/team-member.spec.js
=> added missing tests and fixed button assertion

cypress/integration/v2/blocks/accordion.spec.js, cypress/integration/v2/blocks/blockquote.spec.js, cypress/integration/v2/blocks/blog-posts.spec.js, cypress/integration/v2/blocks/card.spec.js, cypress/integration/v2/blocks/column.spec.js, cypress/integration/v2/blocks/container.spec.js, cypress/integration/v2/blocks/count-up.spec.js, cypress/integration/v2/blocks/cta.spec.js, cypress/integration/v2/blocks/feature-grid.spec.js, cypress/integration/v2/blocks/header.spec.js, cypress/integration/v2/blocks/icon.spec.js, cypress/integration/v2/blocks/image-box.spec.js, cypress/integration/v2/blocks/notification.spec.js, cypress/integration/v2/blocks/number-box.spec.js, cypress/integration/v2/blocks/pricing-box.spec.js, cypress/integration/v2/blocks/team-member.spec.js, cypress/integration/v2/blocks/testimonial.spec.js, cypress/integration/v2/blocks/text.spec.js
=> changed padding values in blocks

cypress/integration/v2/blocks/blockquote.spec.js, cypress/integration/v2/blocks/blog-posts.spec.js, cypress/integration/v2/blocks/card.spec.js, cypress/integration/v2/blocks/column.spec.js, cypress/integration/v2/blocks/container.spec.js, cypress/integration/v2/blocks/count-up.spec.js, cypress/integration/v2/blocks/cta.spec.js, cypress/integration/v2/blocks/feature-grid.spec.js, cypress/integration/v2/blocks/feature.spec.js, cypress/integration/v2/blocks/header.spec.js, cypress/integration/v2/blocks/notification.spec.js, cypress/integration/v2/blocks/number-box.spec.js, cypress/integration/v2/blocks/pricing-box.spec.js, cypress/integration/v2/blocks/team-member.spec.js, cypress/integration/v2/blocks/testimonial.spec.js, cypress/support/gutenberg/commands/controls.js, cypress/support/stackable/commands/controls.js, cypress/support/stackable/helpers/index.js
Fixes #137 
Fixes #141 
Pagination tests are passing:
Tested the latest commit of container link test to Card, Blockquote & CTA. Tests are passing.
=> Container link & pagination test

cypress/support/stackable/helpers/advanced.js
=> Custom attributes test

cypress/integration/v2/features/optimization-settings.spec.js
=> added tests for optimization settings

cypress/integration/v2/blocks/column.spec.js, cypress/support/gutenberg/commands/assertions.js, cypress/support/gutenberg/commands/blocks.js, cypress/support/gutenberg/plugins/blockSnapshots.js
=> Added blocksnapshots to ugb/column. Revised blockSnapshots

cypress/integration/v2/features/global-settings/global-colors/adjust-global-color.spec.js, cypress/integration/v2/features/global-settings/global-colors/change-global-color.spec.js, cypress/integration/v2/features/global-settings/global-colors/delete-global-color.spec.js, cypress/integration/v2/features/global-settings/global-colors/index.js, cypress/integration/v2/features/global-settings/global-colors/native-global-color.spec.js, cypress/support/gutenberg/commands/controls.js, cypress/support/gutenberg/commands/editor.js, cypress/support/stackable/commands/global-settings.js
Fixes #160, fixes #173
All tests passing (Global Colors, Optimization Settings)
=> Fixes Global Colors test

.github/workflows/e2e-test-wp55.yml, .github/workflows/e2e-test-wp56.yml, .github/workflows/e2e-test-wp57.yml, .github/workflows/e2e-test.yml, .wp-env.override.json, readme.md
Added multiple workflows for e2e-testing.
By default, pull request now triggers workflows. To disable the actions completely, add [skip ci] to every commit.
=> Added multiple workflows. 

cypress/integration/v2/other-tests.spec.js
added code to handle the next element to check if this is the premium stylesheet
=> trigger workflow run

cypress/integration/v2/features/dynamic-content/other-tests.spec.js, cypress/support/gutenberg/commands/toolbar.js, cypress/support/gutenberg/util.js, cypress/support/index.js, cypress/support/stackable/commands/toolbar.js
=> test: multiple dynamic content in one line

cypress/support/stackable/commands/blocks.js
Reverts gambitph/Stackable-e2e-tests#224
=> Revert "Added delay to typeBlock"
